#!/usr/bin/env bash

set -e
path=$(dirname "$0")
source ${path}/dd-base.sh

${path}/ddrush sql-dump --gzip --structure-tables-list=cache,cache_*,history,search_*,sessions,watchdog --result-file=../build/ref/${SITE_CODE}_$(date +%Y%m%d\-%H%M).sql
