#!/bin/bash

set -e
path=$(dirname "$0")
source ${path}/d8d-base.sh

# Use the Drush installed by Composer.
drush="vendor/bin/drush --root=${DRUPAL_ROOT}"

${drush} sql-dump --gzip --result-file=../build/ref/${SITE_CODE}_$(date +%Y%m%d\-%H%M).sql
