#!/usr/bin/env bash

set -e
path=$(dirname "$0")
source ${path}/dd-base.sh

# Use the Drupal Console installed by Composer.
drupal="vendor/bin/drupal --root=$drupal_root $@"

docker-compose exec --user www-data ${WEB_SERVICE} bash -ci "$drupal"
