#!/usr/bin/env bash

set -e
path=$(dirname "$0")
source ${path}/d8d-base.sh

# Use the Drupal Console installed by Composer.
drupal="vendor/bin/drupal --root=${DRUPAL_ROOT} $@"

docker-compose exec --user www-data ${WEB_SERVICE} bash -ci "$drupal"
